# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(279, 222)
        MainWindow.setMinimumSize(QtCore.QSize(279, 222))
        MainWindow.setMaximumSize(QtCore.QSize(279, 222))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 281, 201))
        self.tabWidget.setMaximumSize(QtCore.QSize(281, 371))
        self.tabWidget.setObjectName("tabWidget")
        self.windows_activate = QtWidgets.QWidget()
        self.windows_activate.setObjectName("windows_activate")
        self.windows_go = QtWidgets.QPushButton(self.windows_activate)
        self.windows_go.setGeometry(QtCore.QRect(60, 130, 151, 41))
        self.windows_go.setStyleSheet("font: 14pt \"微软雅黑\";")
        self.windows_go.setObjectName("windows_go")
        self.windows_key = QtWidgets.QLabel(self.windows_activate)
        self.windows_key.setGeometry(QtCore.QRect(10, 50, 31, 20))
        self.windows_key.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.windows_key.setObjectName("windows_key")
        self.windows_key_input = QtWidgets.QLineEdit(self.windows_activate)
        self.windows_key_input.setGeometry(QtCore.QRect(90, 50, 171, 20))
        self.windows_key_input.setText("")
        self.windows_key_input.setObjectName("windows_key_input")
        self.windows_ver = QtWidgets.QComboBox(self.windows_activate)
        self.windows_ver.setGeometry(QtCore.QRect(90, 10, 171, 22))
        self.windows_ver.setEditable(False)
        self.windows_ver.setCurrentText("")
        self.windows_ver.setMaxVisibleItems(3)
        self.windows_ver.setDuplicatesEnabled(False)
        self.windows_ver.setObjectName("windows_ver")
        self.windows_ver.addItem("")
        self.windows_ver.addItem("")
        self.windows_ver.addItem("")
        self.windows = QtWidgets.QLabel(self.windows_activate)
        self.windows.setGeometry(QtCore.QRect(10, 10, 71, 20))
        self.windows.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.windows.setObjectName("windows")
        self.windows_server_input = QtWidgets.QLineEdit(self.windows_activate)
        self.windows_server_input.setGeometry(QtCore.QRect(90, 90, 171, 20))
        self.windows_server_input.setText("")
        self.windows_server_input.setObjectName("windows_server_input")
        self.windows_server = QtWidgets.QLabel(self.windows_activate)
        self.windows_server.setGeometry(QtCore.QRect(10, 90, 51, 20))
        self.windows_server.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.windows_server.setObjectName("windows_server")
        self.tabWidget.addTab(self.windows_activate, "")
        self.office_activate = QtWidgets.QWidget()
        self.office_activate.setObjectName("office_activate")
        self.office_ver = QtWidgets.QComboBox(self.office_activate)
        self.office_ver.setGeometry(QtCore.QRect(70, 10, 191, 22))
        self.office_ver.setEditable(False)
        self.office_ver.setCurrentText("")
        self.office_ver.setMaxVisibleItems(12)
        self.office_ver.setDuplicatesEnabled(False)
        self.office_ver.setObjectName("office_ver")
        self.office_ver.addItem("")
        self.office_ver.addItem("")
        self.office_ver.addItem("")
        self.office_ver.addItem("")
        self.office_ver.addItem("")
        self.office_ver.addItem("")
        self.office_ver.addItem("")
        self.office_ver.addItem("")
        self.office_ver.addItem("")
        self.office_ver.addItem("")
        self.office_ver.addItem("")
        self.office_ver.addItem("")
        self.office = QtWidgets.QLabel(self.office_activate)
        self.office.setGeometry(QtCore.QRect(10, 10, 71, 20))
        self.office.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.office.setObjectName("office")
        self.office_key_input = QtWidgets.QLineEdit(self.office_activate)
        self.office_key_input.setGeometry(QtCore.QRect(70, 50, 191, 20))
        self.office_key_input.setText("")
        self.office_key_input.setObjectName("office_key_input")
        self.office_go = QtWidgets.QPushButton(self.office_activate)
        self.office_go.setGeometry(QtCore.QRect(60, 130, 151, 41))
        self.office_go.setStyleSheet("font: 14pt \"微软雅黑\";")
        self.office_go.setObjectName("office_go")
        self.office_key = QtWidgets.QLabel(self.office_activate)
        self.office_key.setGeometry(QtCore.QRect(10, 50, 51, 20))
        self.office_key.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.office_key.setObjectName("office_key")
        self.office_server_input = QtWidgets.QLineEdit(self.office_activate)
        self.office_server_input.setGeometry(QtCore.QRect(70, 90, 191, 20))
        self.office_server_input.setText("")
        self.office_server_input.setObjectName("office_server_input")
        self.office_server = QtWidgets.QLabel(self.office_activate)
        self.office_server.setGeometry(QtCore.QRect(10, 90, 51, 20))
        self.office_server.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.office_server.setObjectName("office_server")
        self.tabWidget.addTab(self.office_activate, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.windows_ver.setCurrentIndex(-1)
        self.office_ver.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "kms激活工具"))
        self.windows_go.setText(_translate("MainWindow", "Activate"))
        self.windows_key.setText(_translate("MainWindow", "key:"))
        self.windows_key_input.setPlaceholderText(_translate("MainWindow", "可自行输入key"))
        self.windows_ver.setItemText(0, _translate("MainWindow", "Windows 10"))
        self.windows_ver.setItemText(1, _translate("MainWindow", "Windows 8"))
        self.windows_ver.setItemText(2, _translate("MainWindow", "Windows 7"))
        self.windows.setText(_translate("MainWindow", "Windows："))
        self.windows_server_input.setPlaceholderText(_translate("MainWindow", "可自行输入服务器地址"))
        self.windows_server.setText(_translate("MainWindow", "server:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.windows_activate), _translate("MainWindow", "Windows激活"))
        self.office_ver.setItemText(0, _translate("MainWindow", "Office 专业增强版 2019"))
        self.office_ver.setItemText(1, _translate("MainWindow", "Office 专业增强版 2016"))
        self.office_ver.setItemText(2, _translate("MainWindow", "Office 专业增强版 2013"))
        self.office_ver.setItemText(3, _translate("MainWindow", "Office 标准版 2019"))
        self.office_ver.setItemText(4, _translate("MainWindow", "Office 标准版 2016"))
        self.office_ver.setItemText(5, _translate("MainWindow", "Office 标准版 2013"))
        self.office_ver.setItemText(6, _translate("MainWindow", "Visio 专业版 2019"))
        self.office_ver.setItemText(7, _translate("MainWindow", "Visio 标准版 2019"))
        self.office_ver.setItemText(8, _translate("MainWindow", "Visio 专业版 2016"))
        self.office_ver.setItemText(9, _translate("MainWindow", "Visio 标准版 2019"))
        self.office_ver.setItemText(10, _translate("MainWindow", "Visio 专业版 2013"))
        self.office_ver.setItemText(11, _translate("MainWindow", "Visio 标准版 2013"))
        self.office.setText(_translate("MainWindow", "Office："))
        self.office_key_input.setPlaceholderText(_translate("MainWindow", "可自行输入key"))
        self.office_go.setText(_translate("MainWindow", "Activate"))
        self.office_key.setText(_translate("MainWindow", "key:"))
        self.office_server_input.setPlaceholderText(_translate("MainWindow", "可自行输入服务器地址"))
        self.office_server.setText(_translate("MainWindow", "server:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.office_activate), _translate("MainWindow", "Office激活"))
